---
root: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

  project:
  - "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - prettier
  - jest

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - standard

  - plugin:jest/recommended
  - plugin:jest/style

  # This one should come last
  - plugin:prettier/recommended

rules:
  prettier/prettier: error
  # this prevents method overloading, and tsc will fail for duplicate class members anyway
  "no-dupe-class-members": off
  # explicit any will silently disable a lot of type checking, try to abstain as much as possible!
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-unused-vars":        [error, {argsIgnorePattern: "^_"}]
  # this fix is needed for optional chaining. can hopefully be removed, when @typescript-eslint default configs get updated
  "no-unused-expressions": "off"
  "@typescript-eslint/no-unused-expressions": "error"
  "@typescript-eslint/no-non-null-assertion": off
  no-restricted-imports:
    - error
    - name: "@babylonjs/core"
      message: "Don't import from @babylonjs/core, use a direct import instead! See https://doc.babylonjs.com/features/es6_support#tree-shaking"
    - name: "@babylonjs/materials"
      message: "Don't import from @babylonjs/materials, use a direct import instead! See https://doc.babylonjs.com/features/es6_support#tree-shaking"
